name: ci

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE

  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [16, 17, 18, 19, 20]
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: "yarn"
      - run: |
          yarn install --frozen-lockfile
          yarn build
